# this is the boilerplate crd def that controller-gen reads and modifies with the
# contents from shared_secret_type.go
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedsecrets.sharedresource.openshift.io
  annotations:
    displayName: SharedSecret
    description: Extension for sharing Secrets across Namespaces
spec:
  scope: Cluster
  group: sharedresource.openshift.io
  names:
    plural: sharedsecrets
    singular: sharedsecret
    kind: SharedSecret
    listKind: SharedSecretList
  versions:
    - name: v1alpha1
      served: true
      storage: true

