# this is the boilerplate crd def that controller-gen reads and modifies with the
# contents from share_type.go
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedresources.storage.openshift.io
  annotations:
    displayName: SharedResource
    description: Extension for sharing ConfigMaps and Secrets across Namespaces
spec:
  scope: Cluster
  group: storage.openshift.io
  names:
    plural: sharedresources
    singular: sharedresource
    kind: SharedResource
    listKind: SharedResourceList
  versions:
  - name: v1alpha1
    served: true
    storage: true
