# When https://issues.redhat.com/browse/STOR-828 is implemented in OpenShift, and the Shared Resource CSI Driver can be
# deemed safe for restricted users, this ClusterRole and its associated binding can be removed.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-shared-resource-privileged-role
rules:
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["my-csi-scc-from-restricted"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]