---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-hostpathplugin
  namespace: openshift-cluster-csi-drivers
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: csi-hostpathplugin
