apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shared-resource-my-share
rules:
  - apiGroups:
      - sharedresource.openshift.io
    resources:
      - shares
    resourceNames:
      - my-share
    verbs:
      - get
      - list
      - watch