apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-resource-my-share-bc
  namespace: my-csi-app-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-resource-my-share-bc
subjects:
  - kind: ServiceAccount
    name: builder
    namespace: my-csi-app-namespace
